name: Tests
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

      - name: Build
        run: yarn build --ignore=@strapi/design-system-docs

      - name: Run TSC
        run: yarn test:ts
  lint:
    name: 'Lint'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run prettier
        run: yarn prettier:check
  unit_tests:
    name: 'unit tests'
    needs: [lint, typecheck]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install

      - name: Build
        run: yarn build --ignore=@strapi/design-system-docs

      - name: Unit / Integration tests
        run: yarn test
  e2e_tests:
    name: 'e2e tests (browser: ${{ matrix.browser }})'
    needs: [lint, typecheck, unit_tests]
    runs-on: macos-latest
    strategy:
      matrix:
        browser: [chromium, webkit, firefox]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - run: yarn install

      - name: Install Playwright
        run: npx playwright@1.37.0 install

      - name: Build
        run: yarn build

      - name: Start storybook
        working-directory: ./docs/storybook-static
        run: yarn add -D http-server && yarn http-server -p 6006 &

      - name: Run the tests
        run: yarn test:e2e:ci -- --project=${{ matrix.browser }}
